# Generated by Django 5.0.1 on 2024-04-14 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0002_remove_mentortodo_begindate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="goal.goal",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="goal.goal",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="goal.goal",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="websites",
                to="goal.goal",
            ),
        ),
    ]
